# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://centime.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: '/cieyongwe.github.io/'

logo: "/assets/images/logo.png"

# Title of the Site
title: Cie Yongwe
# Description of the Site
description: Spectacles vivants et cie
# URL of Image of the Site
site-image: /assets/images/logo.png
# Keywords of the Site
site-keywords: Spectacle, Compagnie, Poésie, Musique
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /uploads/dome-lune.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: compagnie.yongwe@gmail.com
facebook_username: cieyongwe
youtube_channel_id: @cieyongwe3136

# Google Analytics
google-analytics: 


# Name of the Author
author-name: Cie Yongwe
# URL for the Image of the Author
author-image: /assets/images/authors.png
# 60 Words About the Author
author-about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)


# Defaults
defaults:
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
